//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""c3919879-24a2-434b-83ac-9babfecbdc26"",
            ""actions"": [
                {
                    ""name"": ""headButton"",
                    ""type"": ""Button"",
                    ""id"": ""3f365351-169a-45a4-af92-566e2ccf7403"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""chestButton"",
                    ""type"": ""Button"",
                    ""id"": ""56862b55-e450-4529-b055-92a0b6dd60f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""handButton"",
                    ""type"": ""Button"",
                    ""id"": ""d5a3b93a-63e3-4eff-a060-d77226209898"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cbf0a6be-d52b-4fe9-b7e9-446d9a86474c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""headButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38ed260c-9d3d-4558-9bcf-a51ed64e79e1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""chestButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d456fa21-06a8-4064-9599-834235cc429e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""handButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_headButton = m_Player.FindAction("headButton", throwIfNotFound: true);
        m_Player_chestButton = m_Player.FindAction("chestButton", throwIfNotFound: true);
        m_Player_handButton = m_Player.FindAction("handButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_headButton;
    private readonly InputAction m_Player_chestButton;
    private readonly InputAction m_Player_handButton;
    public struct PlayerActions
    {
        private @InputMaster m_Wrapper;
        public PlayerActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @headButton => m_Wrapper.m_Player_headButton;
        public InputAction @chestButton => m_Wrapper.m_Player_chestButton;
        public InputAction @handButton => m_Wrapper.m_Player_handButton;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @headButton.started += instance.OnHeadButton;
            @headButton.performed += instance.OnHeadButton;
            @headButton.canceled += instance.OnHeadButton;
            @chestButton.started += instance.OnChestButton;
            @chestButton.performed += instance.OnChestButton;
            @chestButton.canceled += instance.OnChestButton;
            @handButton.started += instance.OnHandButton;
            @handButton.performed += instance.OnHandButton;
            @handButton.canceled += instance.OnHandButton;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @headButton.started -= instance.OnHeadButton;
            @headButton.performed -= instance.OnHeadButton;
            @headButton.canceled -= instance.OnHeadButton;
            @chestButton.started -= instance.OnChestButton;
            @chestButton.performed -= instance.OnChestButton;
            @chestButton.canceled -= instance.OnChestButton;
            @handButton.started -= instance.OnHandButton;
            @handButton.performed -= instance.OnHandButton;
            @handButton.canceled -= instance.OnHandButton;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnHeadButton(InputAction.CallbackContext context);
        void OnChestButton(InputAction.CallbackContext context);
        void OnHandButton(InputAction.CallbackContext context);
    }
}
